In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle
import requests
import json
from pathlib import Path
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from collections import Counter
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from collections import Counter
from imblearn.over_sampling import RandomOverSampler 

In [2]:
data = Path('./results/DataProcessingExtractFile-RawData.csv')
df = pd.read_csv(data)
df.head(10)

Diabetes_Status  HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
0                1     1.0       1.0        1.0          4     1.0     0.0   
1                1     0.0       0.0        0.0          3     1.0     0.0   
2                1     1.0       1.0        1.0          3     0.0     0.0   
3                1     1.0       0.0        1.0          3     0.0     0.0   
4                1     1.0       1.0        1.0          2     0.0     0.0   
5                1     1.0       1.0        1.0          3     1.0     0.0   
6                1     1.0       0.0        1.0          4     1.0     0.0   
7                1     1.0       1.0        1.0          3     1.0     0.0   
8                2     1.0       1.0        1.0          4     1.0     0.0   
9                1     0.0       0.0        1.0          2     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   
5                   0.0           1.0     1.0  ...            1.0   
6                   0.0           0.0     0.0  ...            1.0   
7                   0.0           1.0     0.0  ...            1.0   
8                   1.0           0.0     1.0  ...            1.0   
9                   0.0           0.0     0.0  ...            1.0   

   NoDocbcCost  GenHlth  Mental_Health_Range  Physical_Health_Range  DiffWalk  \
0          0.0      5.0                    4                      3       1.0   
1          1.0      3.0                    1                      1       0.0   
2          1.0      5.0                    6                      6       1.0   
3          0.0      2.0                    1                      1       0.0   
4          0.0      2.0                    1                      1       0.0   
5          0.0      2.0                    1                      1       0.0   
6          0.0      3.0                    1                      3       0.0   
7          0.0      3.0                    1                      1       1.0   
8          0.0      5.0                    6                      6       1.0   
9          0.0      2.0                    1                      1       0.0   

   Sex   Age  Education  Income  
0  0.0   9.0        4.0     3.0  
1  0.0   7.0        6.0     1.0  
2  0.0   9.0        4.0     8.0  
3  0.0  11.0        3.0     6.0  
4  0.0  11.0        5.0     4.0  
5  1.0  10.0        6.0     8.0  
6  0.0   9.0        6.0     7.0  
7  0.0  11.0        4.0     4.0  
8  0.0   9.0        5.0     1.0  
9  1.0   8.0        4.0     3.0  

[10 rows x 22 columns]

In [3]:
# Random Forest Model

X = df.copy()
X = df.drop(df.columns[[0]], axis=1)
X.head()

HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
0     1.0       1.0        1.0          4     1.0     0.0   
1     0.0       0.0        0.0          3     1.0     0.0   
2     1.0       1.0        1.0          3     0.0     0.0   
3     1.0       0.0        1.0          3     0.0     0.0   
4     1.0       1.0        1.0          2     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  AnyHealthcare  \
0                   0.0           0.0     0.0      1.0  ...            1.0   
1                   0.0           1.0     0.0      0.0  ...            0.0   
2                   0.0           0.0     1.0      0.0  ...            1.0   
3                   0.0           1.0     1.0      1.0  ...            1.0   
4                   0.0           1.0     1.0      1.0  ...            1.0   

   NoDocbcCost  GenHlth  Mental_Health_Range  Physical_Health_Range  DiffWalk  \
0          0.0      5.0                    4                      3       1.0   
1          1.0      3.0                    1                      1       0.0   
2          1.0      5.0                    6                      6       1.0   
3          0.0      2.0                    1                      1       0.0   
4          0.0      2.0                    1                      1       0.0   

   Sex   Age  Education  Income  
0  0.0   9.0        4.0     3.0  
1  0.0   7.0        6.0     1.0  
2  0.0   9.0        4.0     8.0  
3  0.0  11.0        3.0     6.0  
4  0.0  11.0        5.0     4.0  

[5 rows x 21 columns]

In [4]:
y = df["Diabetes_Status"].ravel()
y[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1])

In [5]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y,
                                                    random_state=78,
                                                    stratify=y)
X_train.head()

HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
173928     1.0       0.0        1.0          4     0.0     1.0   
239730     0.0       1.0        1.0          3     1.0     0.0   
81199      0.0       1.0        1.0          2     0.0     0.0   
160865     0.0       0.0        1.0          2     0.0     0.0   
121583     0.0       0.0        1.0          4     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
173928                   0.0           1.0     1.0      1.0  ...   
239730                   0.0           0.0     0.0      0.0  ...   
81199                    0.0           1.0     0.0      1.0  ...   
160865                   0.0           0.0     1.0      1.0  ...   
121583                   0.0           1.0     1.0      1.0  ...   

        AnyHealthcare  NoDocbcCost  GenHlth  Mental_Health_Range  \
173928            1.0          0.0      3.0                    1   
239730            1.0          1.0      5.0                    2   
81199             1.0          0.0      2.0                    1   
160865            1.0          0.0      2.0                    1   
121583            1.0          0.0      3.0                    1   

        Physical_Health_Range  DiffWalk  Sex   Age  Education  Income  
173928                      1       0.0  0.0  11.0        3.0     7.0  
239730                      1       1.0  0.0   7.0        3.0     4.0  
81199                       1       0.0  0.0   6.0        6.0     8.0  
160865                      1       0.0  1.0   5.0        6.0     8.0  
121583                      1       1.0  0.0   9.0        6.0     8.0  

[5 rows x 21 columns]

In [6]:
print('y_train dataset shape {}'.format(Counter(y_train)))

y_train dataset shape Counter({1: 160277, 2: 29983})


In [7]:
# make a balanced dataset before training
ros = RandomOverSampler(random_state=78)
X_res, y_res = ros.fit_resample(X_train, y_train)
print('Resampled dataset shape {}'.format(Counter(y_res)))

Resampled dataset shape Counter({1: 160277, 2: 160277})


In [74]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=48, max_depth=8, random_state=78) 

In [75]:
# Fitting the model
rf_model = rf_model.fit(X_res, y_res)

In [76]:
# evaluate the training accuracy first, based on the data before oversampling
pred_train=rf_model.predict(X_train)
cm_train = confusion_matrix(y_train, pred_train)
cmt_df = pd.DataFrame(
    cm_train, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cmt_df

Predicted 0  Predicted 1
Actual 0       114205        46072
Actual 1         6526        23457

In [77]:
# Calculate the accuracy score on trained set.
acc_score = accuracy_score(y_train, pred_train)
acc_score

0.7235467255334805

In [78]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test)
predictions

array([1, 2, 1, ..., 2, 2, 2])

In [79]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

Predicted 0  Predicted 1
Actual 0        37977        15449
Actual 1         2263         7731

In [80]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.7207190160832545

In [59]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0        37076        16350
Actual 1         2193         7801

Accuracy Score : 0.7076158940397351
Classification Report
              precision    recall  f1-score   support

           1       0.94      0.69      0.80     53426
           2       0.32      0.78      0.46      9994

    accuracy                           0.71     63420
   macro avg       0.63      0.74      0.63     63420
weighted avg       0.85      0.71      0.75     63420



In [14]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.07559454, 0.04137204, 0.00733121, 0.06562755, 0.03519849,
       0.01200091, 0.01906504, 0.0291436 , 0.03507462, 0.02743144,
       0.01065297, 0.00974255, 0.01619467, 0.11984133, 0.03517535,
       0.04278718, 0.02642093, 0.03010533, 0.16798407, 0.07790715,
       0.11534905])

In [15]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.1679840664228351, 'Age'),
 (0.11984132700379665, 'GenHlth'),
 (0.11534904628308855, 'Income'),
 (0.0779071460069288, 'Education'),
 (0.07559454287136996, 'HighBP'),
 (0.06562755405377199, 'BMI_Range'),
 (0.04278718273108797, 'Physical_Health_Range'),
 (0.04137204096749132, 'HighChol'),
 (0.035198486378112535, 'Smoker'),
 (0.03517535048696076, 'Mental_Health_Range'),
 (0.03507461548958903, 'Fruits'),
 (0.03010532511586743, 'Sex'),
 (0.02914359729786202, 'PhysActivity'),
 (0.027431444774875663, 'Veggies'),
 (0.02642093363928398, 'DiffWalk'),
 (0.01906504191106784, 'HeartDiseaseorAttack'),
 (0.016194665792445398, 'NoDocbcCost'),
 (0.012000907161827858, 'Stroke'),
 (0.010652971344726257, 'HvyAlcoholConsump'),
 (0.009742546356346811, 'AnyHealthcare'),
 (0.007331207910664226, 'CholCheck')]

In [16]:
pickle.dump(rf_model, open('model.pkl','wb'))