In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle
import requests
import json
from pathlib import Path
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from collections import Counter
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from collections import Counter
from imblearn.over_sampling import RandomOverSampler 

In [2]:
data = Path('./results/DataProcessingExtractFile-RawData.csv')
df = pd.read_csv(data)
df.head(10)

Diabetes_Status  HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
0                1     1.0       1.0        1.0          4     1.0     0.0   
1                1     0.0       0.0        0.0          3     1.0     0.0   
2                1     1.0       1.0        1.0          3     0.0     0.0   
3                1     1.0       0.0        1.0          3     0.0     0.0   
4                1     1.0       1.0        1.0          2     0.0     0.0   
5                1     1.0       1.0        1.0          3     1.0     0.0   
6                1     1.0       0.0        1.0          4     1.0     0.0   
7                1     1.0       1.0        1.0          3     1.0     0.0   
8                2     1.0       1.0        1.0          4     1.0     0.0   
9                1     0.0       0.0        1.0          2     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   
5                   0.0           1.0     1.0  ...            1.0   
6                   0.0           0.0     0.0  ...            1.0   
7                   0.0           1.0     0.0  ...            1.0   
8                   1.0           0.0     1.0  ...            1.0   
9                   0.0           0.0     0.0  ...            1.0   

   NoDocbcCost  GenHlth  Mental_Health_Range  Physical_Health_Range  DiffWalk  \
0          0.0      5.0                    4                      3       1.0   
1          1.0      3.0                    1                      1       0.0   
2          1.0      5.0                    6                      6       1.0   
3          0.0      2.0                    1                      1       0.0   
4          0.0      2.0                    1                      1       0.0   
5          0.0      2.0                    1                      1       0.0   
6          0.0      3.0                    1                      3       0.0   
7          0.0      3.0                    1                      1       1.0   
8          0.0      5.0                    6                      6       1.0   
9          0.0      2.0                    1                      1       0.0   

   Sex   Age  Education  Income  
0  0.0   9.0        4.0     3.0  
1  0.0   7.0        6.0     1.0  
2  0.0   9.0        4.0     8.0  
3  0.0  11.0        3.0     6.0  
4  0.0  11.0        5.0     4.0  
5  1.0  10.0        6.0     8.0  
6  0.0   9.0        6.0     7.0  
7  0.0  11.0        4.0     4.0  
8  0.0   9.0        5.0     1.0  
9  1.0   8.0        4.0     3.0  

[10 rows x 22 columns]

In [3]:
# Random Forest Model

X = df.copy()
X = df.drop(df.columns[[0]], axis=1)
X.head()

HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
0     1.0       1.0        1.0          4     1.0     0.0   
1     0.0       0.0        0.0          3     1.0     0.0   
2     1.0       1.0        1.0          3     0.0     0.0   
3     1.0       0.0        1.0          3     0.0     0.0   
4     1.0       1.0        1.0          2     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  AnyHealthcare  \
0                   0.0           0.0     0.0      1.0  ...            1.0   
1                   0.0           1.0     0.0      0.0  ...            0.0   
2                   0.0           0.0     1.0      0.0  ...            1.0   
3                   0.0           1.0     1.0      1.0  ...            1.0   
4                   0.0           1.0     1.0      1.0  ...            1.0   

   NoDocbcCost  GenHlth  Mental_Health_Range  Physical_Health_Range  DiffWalk  \
0          0.0      5.0                    4                      3       1.0   
1          1.0      3.0                    1                      1       0.0   
2          1.0      5.0                    6                      6       1.0   
3          0.0      2.0                    1                      1       0.0   
4          0.0      2.0                    1                      1       0.0   

   Sex   Age  Education  Income  
0  0.0   9.0        4.0     3.0  
1  0.0   7.0        6.0     1.0  
2  0.0   9.0        4.0     8.0  
3  0.0  11.0        3.0     6.0  
4  0.0  11.0        5.0     4.0  

[5 rows x 21 columns]

In [4]:
y = df["Diabetes_Status"].ravel()
y[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1])

In [19]:
ros = RandomOverSampler(random_state=78)
Xpre_res, ypre_res = ros.fit_resample(X, y)

In [21]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(Xpre_res, 
                                                    ypre_res,
                                                    random_state=78,
                                                    stratify=ypre_res)
X_train.head()

HighBP  HighChol  CholCheck  BMI_Range  Smoker  Stroke  \
97154      0.0       1.0        1.0          3     1.0     0.0   
252311     1.0       1.0        1.0          3     0.0     0.0   
367766     1.0       1.0        1.0          3     0.0     0.0   
252680     1.0       0.0        1.0          3     0.0     0.0   
284016     1.0       1.0        1.0          4     1.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
97154                    0.0           1.0     1.0      1.0  ...   
252311                   0.0           0.0     1.0      1.0  ...   
367766                   0.0           1.0     1.0      1.0  ...   
252680                   0.0           1.0     0.0      0.0  ...   
284016                   0.0           1.0     1.0      1.0  ...   

        AnyHealthcare  NoDocbcCost  GenHlth  Mental_Health_Range  \
97154             1.0          0.0      1.0                    2   
252311            1.0          0.0      4.0                    1   
367766            1.0          0.0      3.0                    1   
252680            1.0          1.0      4.0                    1   
284016            1.0          0.0      2.0                    6   

        Physical_Health_Range  DiffWalk  Sex   Age  Education  Income  
97154                       1       0.0  0.0  10.0        6.0     5.0  
252311                      2       1.0  1.0   8.0        3.0     1.0  
367766                      3       1.0  0.0  12.0        5.0     3.0  
252680                      1       0.0  0.0   6.0        6.0     5.0  
284016                      1       1.0  0.0   8.0        6.0     1.0  

[5 rows x 21 columns]

In [22]:
print('y_train dataset shape {}'.format(Counter(y_train)))

y_train dataset shape Counter({1: 160277, 2: 160277})


In [23]:
# make a balanced dataset before training
ros = RandomOverSampler(random_state=78)
X_res, y_res = ros.fit_resample(X_train, y_train)
print('Resampled dataset shape {}'.format(Counter(y_res)))

Resampled dataset shape Counter({1: 160277, 2: 160277})


In [24]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 

In [25]:
# Fitting the model
rf_model = rf_model.fit(X_res, y_res)

In [26]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test)
predictions

array([2, 1, 2, ..., 1, 1, 2])

In [27]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

Predicted 0  Predicted 1
Actual 0        44951         8475
Actual 1         2581        50845

In [28]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.8965297795081046

In [29]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0        44951         8475
Actual 1         2581        50845

Accuracy Score : 0.8965297795081046
Classification Report
              precision    recall  f1-score   support

           1       0.95      0.84      0.89     53426
           2       0.86      0.95      0.90     53426

    accuracy                           0.90    106852
   macro avg       0.90      0.90      0.90    106852
weighted avg       0.90      0.90      0.90    106852



In [30]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.08156671, 0.0405992 , 0.00712863, 0.06529562, 0.03454873,
       0.01199752, 0.01908216, 0.027577  , 0.03459165, 0.02759259,
       0.01049596, 0.00979622, 0.01608695, 0.11595606, 0.03578219,
       0.04358694, 0.02571868, 0.0299325 , 0.16815576, 0.07863311,
       0.11587583])

In [31]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.16815575772188043, 'Age'),
 (0.11595605519316285, 'GenHlth'),
 (0.11587583241102888, 'Income'),
 (0.08156670933502107, 'HighBP'),
 (0.07863311319294153, 'Education'),
 (0.06529561620999164, 'BMI_Range'),
 (0.043586941495698237, 'Physical_Health_Range'),
 (0.04059920236669907, 'HighChol'),
 (0.03578218509359731, 'Mental_Health_Range'),
 (0.03459165172433939, 'Fruits'),
 (0.034548732259074066, 'Smoker'),
 (0.02993250311503878, 'Sex'),
 (0.027592586302238188, 'Veggies'),
 (0.027577002669223, 'PhysActivity'),
 (0.025718680741525966, 'DiffWalk'),
 (0.019082162748311503, 'HeartDiseaseorAttack'),
 (0.01608694832186756, 'NoDocbcCost'),
 (0.01199751619464798, 'Stroke'),
 (0.01049595590416554, 'HvyAlcoholConsump'),
 (0.009796220186110474, 'AnyHealthcare'),
 (0.00712862681343664, 'CholCheck')]

In [32]:
pickle.dump(rf_model, open('model.pkl','wb'))